const SENSOR_SLOTS = [
  {
    id: "imu1",
    label: "IMU 1",
    bodyPart: "Right Wrist",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu2",
    label: "IMU 2",
    bodyPart: "Left Wrist",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu3",
    label: "IMU 3",
    bodyPart: "Right Ankle",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu4",
    label: "IMU 4",
    bodyPart: "Left Ankle",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu5",
    label: "IMU 5",
    bodyPart: "Right Knee",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu6",
    label: "IMU 6",
    bodyPart: "Left Knee",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu7",
    label: "IMU 7",
    bodyPart: "Lower Back",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu8",
    label: "IMU 8",
    bodyPart: "Right Shoulder",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu9",
    label: "IMU 9",
    bodyPart: "Left Shoulder",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu10",
    label: "IMU 10",
    bodyPart: "Head / Neck",
    status: "active",
    color: "#1D9E75",
  },
  {
    id: "imu11",
    label: "IMU 11",
    bodyPart: "Left Footrest 1",
    status: "placeholder",
    group: "footrest_left",
    color: "#6B7280",
  },
  {
    id: "imu12",
    label: "IMU 12",
    bodyPart: "Left Footrest 2",
    status: "placeholder",
    group: "footrest_left",
    color: "#6B7280",
  },
  {
    id: "imu13",
    label: "IMU 13",
    bodyPart: "Left Footrest 3",
    status: "placeholder",
    group: "footrest_left",
    color: "#6B7280",
  },
  {
    id: "imu14",
    label: "IMU 14",
    bodyPart: "Left Footrest 4",
    status: "placeholder",
    group: "footrest_left",
    color: "#6B7280",
  },
  {
    id: "imu15",
    label: "IMU 15",
    bodyPart: "Left Footrest 5",
    status: "placeholder",
    group: "footrest_left",
    color: "#6B7280",
  },
  {
    id: "imu16",
    label: "IMU 16",
    bodyPart: "Left Footrest 6",
    status: "placeholder",
    group: "footrest_left",
    color: "#6B7280",
  },
  {
    id: "imu17",
    label: "IMU 17",
    bodyPart: "Left Footrest 7",
    status: "placeholder",
    group: "footrest_left",
    color: "#6B7280",
  },
  {
    id: "imu18",
    label: "IMU 18",
    bodyPart: "Left Footrest 8",
    status: "placeholder",
    group: "footrest_left",
    color: "#6B7280",
  },
  {
    id: "imu19",
    label: "IMU 19",
    bodyPart: "Right Footrest 1",
    status: "placeholder",
    group: "footrest_right",
    color: "#6B7280",
  },
  {
    id: "imu20",
    label: "IMU 20",
    bodyPart: "Right Footrest 2",
    status: "placeholder",
    group: "footrest_right",
    color: "#6B7280",
  },
  {
    id: "imu21",
    label: "IMU 21",
    bodyPart: "Right Footrest 3",
    status: "placeholder",
    group: "footrest_right",
    color: "#6B7280",
  },
  {
    id: "imu22",
    label: "IMU 22",
    bodyPart: "Right Footrest 4",
    status: "placeholder",
    group: "footrest_right",
    color: "#6B7280",
  },
  {
    id: "imu23",
    label: "IMU 23",
    bodyPart: "Right Footrest 5",
    status: "placeholder",
    group: "footrest_right",
    color: "#6B7280",
  },
  {
    id: "imu24",
    label: "IMU 24",
    bodyPart: "Right Footrest 6",
    status: "placeholder",
    group: "footrest_right",
    color: "#6B7280",
  },
  {
    id: "imu25",
    label: "IMU 25",
    bodyPart: "Right Footrest 7",
    status: "placeholder",
    group: "footrest_right",
    color: "#6B7280",
  },
  {
    id: "imu26",
    label: "IMU 26",
    bodyPart: "Right Footrest 8",
    status: "placeholder",
    group: "footrest_right",
    color: "#6B7280",
  },
];

const CONFIG = {
  LAB_NAME: "Your Lab Name",
  INSTITUTION: "Your Institution",
  /** Offline session recorder (python data_collection_server.py) */
  SESSION_RECORDER_URL: "http://localhost:3000",
  SESSIONS_ROOT_DISPLAY: "E:\\SensorData\\Sessions",
  USE_OFFLINE_SESSION_RECORDER: true,
  VIDEO_STREAM_FPS: 24,
  /** Legacy Flask bridge (optional preview only) */
  FLASK_BASE_URL: "http://localhost:3000",
  FLASK_DATA_URL: "http://localhost:3000",
  FLASK_SYNC_URL: "",
  IMU_POLL_MS: 1000,
  SENSOR_SLOTS,
  /** Body sensors (IMU 1–10) — live hardware expected when deployed */
  ACTIVE_SENSOR_COUNT: 10,
  /** All defined slots including footrest placeholders (IMU 11–26) */
  TOTAL_SENSOR_COUNT: 26,
  PLACEHOLDER_SENSOR_COUNT: 16,
};

export default CONFIG;
