const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, AlignmentType, LevelFormat,
  HeadingLevel, BorderStyle, PageBreak,
} = require("docx");

const PAGE_WIDTH = 12240, PAGE_HEIGHT = 15840;
const MARGIN = 1440;

const doc = new Document({
  creator: "YogaAlign Team",
  title: "YogaAlign – Progress Report",
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 32, bold: true, font: "Arial", color: "1F1147" },
        paragraph: { spacing: { before: 280, after: 160 }, outlineLevel: 0,
          border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "7C3AED", space: 4 } } } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, font: "Arial", color: "5B21B6" },
        paragraph: { spacing: { before: 220, after: 120 }, outlineLevel: 1 } },
    ],
  },
  numbering: {
    config: [
      { reference: "bullets", levels: [
        { level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
        { level: 1, format: LevelFormat.BULLET, text: "○", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 1260, hanging: 360 } } } },
      ] },
      { reference: "timeline", levels: [
        { level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
      ] },
    ],
  },
  sections: [{
    properties: {
      page: { size: { width: PAGE_WIDTH, height: PAGE_HEIGHT },
        margin: { top: MARGIN, right: MARGIN, bottom: MARGIN, left: MARGIN } },
    },
    children: [
      // ---- Title block ----
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 40 },
        children: [new TextRun({ text: "YogaAlign — AI Pose Correction Coach", bold: true, size: 40, color: "1F1147" })],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 40 },
        children: [new TextRun({ text: "Progress Report", bold: true, size: 30, color: "7C3AED" })],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 60 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "CCCCCC", space: 8 } },
        children: [new TextRun({ text: "Date: June 13, 2026", size: 20, color: "666666" })],
      }),

      // ---- 1. Assigned Work ----
      new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun("1. Assigned Work")] }),
      new Paragraph({
        spacing: { after: 120 },
        children: [new TextRun(
          "The team was assigned to build an AI-powered yoga pose correction application that guides a " +
          "practitioner step-by-step through a yoga pose in real time, using camera-based body pose " +
          "estimation and a local (on-device) machine learning model, with an additional local large " +
          "language model (LLM) providing detailed coaching feedback when the user struggles with a step. " +
          "The key requirements assigned were:"
        )],
      }),
      bullet("Detect, in real time, whether the practitioner's body position matches the expected pose for the current step of a yoga asana, using a camera feed."),
      bullet("Break each of 13 selected yoga poses (Standing, Sitting, Prone, and Supine categories) into a sequence of verifiable steps, and guide the user through them one at a time."),
      bullet("Provide actionable, prioritized coaching feedback — including safety-relevant corrections — when the user is stuck on a step, generated by a locally-hosted AI model (no paid cloud APIs)."),
      bullet("Design the system to optionally incorporate wearable motion-sensor (IMU) data alongside the camera feed for improved accuracy, even if sensor data collection is still in progress."),
      bullet("Build a lightweight web application (Node.js/Express backend, browser frontend) that runs the entire pipeline — pose estimation, ML classification, and LLM coaching — locally."),

      // ---- 2. Work Completed ----
      new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun("2. Work Completed")] }),

      new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("2.1 Data Collection & Dataset Preparation")] }),
      bullet("Collected pose-practice recordings from 7 participants across 9 recording sessions (40 individual pose recordings in total), covering all 13 supported yoga poses, captured as sequences of MediaPipe 33-point body landmarks (x, y, z per frame), with synchronized 6-axis IMU sensor packets and per-session metadata."),
      bullet("Collected a second batch of recordings from 8 additional participants (9 further sessions, covering the 7 “Standing” poses), bringing the project to 15 participants / 18 sessions total. This batch has now been merged into training_data.json — see Section 2.2."),
      bullet("Built prepare_dataset_v2.py to convert raw recordings into a labeled training set, applying three key techniques:"),
      bullet("Landmark normalization — translates landmarks so the hip-midpoint is the origin and scales by torso length (shoulder-midpoint to hip-midpoint distance), making the model invariant to the user's distance from the camera and body proportions.", 1),
      bullet("Mirror augmentation — generates left/right-flipped duplicates of every sample (with landmark pairs swapped), doubling the dataset and helping the model generalize to either-side orientation.", 1),
      bullet("Clustering-based step labeling — replaced naive “equal time chunks” labeling with an unsupervised k-means clustering algorithm (implemented from scratch, k-means++ initialization) that groups frames into the natural number of steps per pose, orders clusters chronologically, and smooths the resulting labels with a median filter.", 1),
      bullet("Final dataset spans 74 distinct “step” classes across the 13 supported poses."),

      new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("2.2 Dataset Merge & Model Retraining")] }),
      bullet("Wrote merge_new_participants.py, which applies the same normalization, k-means step-labeling, median smoothing, and mirror-augmentation pipeline as prepare_dataset_v2.py to the new participants' landmark recordings (IMU channels zero-filled, matching the existing 105-feature format), and merges the result into training_data.json."),
      bullet("Dataset grew from 29,116 samples (7 participants) to 66,410 samples (15 participants) — split 56,448 train / 9,962 validation (85/15)."),
      bullet("Retrained the pose-step classifier (TensorFlow.js feedforward network: Dense 256 → Dropout → Dense 128 → Dropout → Dense 64 → Dense 74 softmax) on the merged dataset, using an equivalent training budget (~18 epochs) to the previous run."),
      bullet("Validation accuracy on the merged dataset: 74.38% (val loss 0.6974) — down from the 87.25% figure measured on the smaller 7-participant dataset. This drop is expected, not a regression: the merged set more than doubles the data and adds 8 new participants' Standing-pose recordings, so the model is now being scored on substantially more body-type and form variation than before. The earlier 87.25% reflected strong fit to a narrower set of 7 people; 74.38% is a more realistic measure of generalization to new practitioners."),
      bullet("Follow-up (v3) retraining: the 74 step classes are highly imbalanced (102–3,233 samples per class, ~33x range). Continued training with class-balanced minibatch sampling (each batch drawn uniformly across classes rather than by raw frequency) plus a learning-rate decay schedule (0.001 → 0.0005 → 0.0002 over ~21 epochs) raised validation accuracy from 74.38% to 79.27% (val loss 0.50) — a +4.9 point gain — with no change to the model architecture or 105-feature input format."),
      bullet("Investigated whether incorporating real IMU sensor data could close the remaining gap to 80%+. Finding: the original 7-participant batch (29,116 samples) already contains real, non-zero accelerometer/gyroscope readings — these were never at zero weight. The raw sensor logs captured for the 8 new participants, however, were recorded with the new 10-sensor array and currently report all-zero accelerometer and gyroscope values for every packet (only orientation/quaternion fields are populated), so there is no real accel/gyro data available yet to merge in for that batch. Real IMU integration for the new participants therefore remains blocked on the sensor firmware streaming non-zero accel/gyro values (see Section 5.3 of the User Manual)."),
      bullet("Joint-angle feature engineering (v5): added 12 derived joint-angle features — left/right elbow, knee, hip, shoulder and ankle angles, plus spine-tilt and shoulder-line-tilt angles — computed deterministically from the existing 33 landmarks (pose_features.mjs), growing the input vector from 105 to 117 features. Re-preprocessed the full dataset and retrained from scratch using a two-phase recipe: phase 1 ran 18 epochs with uniform random sampling (mirroring the original v2 baseline), and phase 2 continued for a further 21 epochs with class-balanced minibatch sampling and the same learning-rate decay schedule used for v3 (0.001 -> 0.0005 -> 0.0002 -> 0.0001)."),
      bullet("Result: validation accuracy rose from 79.27% (v3, 105 features) to 81.68% (v5, 117 features, val loss 0.5214) — a +2.4 point gain, and the first result to clear the 80% target. This is now the deployed model."),
      bullet("Updated server.js to compute the same 12 joint-angle features at inference time (via pose_features.mjs) and feed the resulting 117-feature vector to the model, keeping training and real-time inference in sync. Verified end-to-end with a spot-check script (smoke_v5_check.mjs) against held-out training samples."),

      new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("2.3 Local LLM Coaching Integration")] }),
      bullet("Replaced the earlier cloud-based Gemini integration with a fully local Ollama LLM (default model: llama3.2), removing any dependency on external paid APIs."),
      bullet("Implemented the /api/ollama-feedback endpoint, which is triggered when the user has been “stuck” on a step (model detects a violation) for more than 3 seconds, and returns structured JSON coaching feedback."),
      bullet("Added a 10-second cooldown on the frontend to prevent repeated LLM calls while the user continues to adjust."),

      new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("2.4 Application & Verification")] }),
      bullet("Built the end-to-end web application: pose-selection screen, live camera view, step instruction card, and AI feedback panel, in a dark-themed UI."),
      bullet("Hybrid feedback loop: a fast (every 500ms) ML check verifies step completion, while the slower LLM coaching only kicks in for sustained difficulty — balancing responsiveness with depth of feedback."),
      bullet("Smoke-tested the retrained model end-to-end (load → predict) via the TensorFlow.js pipeline to confirm the new model artifacts integrate correctly with server.js."),

      // ---- 3. Ongoing Work ----
      new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun("3. Ongoing Work & Timeline")] }),
      new Paragraph({
        spacing: { after: 120 },
        children: [new TextRun("The following items are in progress or planned, with estimated completion timelines:")],
      }),
      timeline("Live MediaPipe pose integration: Connect the already-loaded MediaPipe Pose model to the live camera feed in app.js. The analysis pipeline (server.js) is fully functional, but the frontend currently sends placeholder landmark data instead of real-time detections.", "~1 week"),
      timeline("Video-upload analysis flow: Re-integrate the existing multer-based video upload pathway with the retrained model so users can also analyze pre-recorded session videos.", "~1 week"),
      timeline("IMU sensor fusion (revised 10-sensor design): The hardware design has been finalized as a 10-sensor IMU array (BNO085-based — one sensor per major limb segment plus upper/lower spine; see User Manual Section 5.3 for the full placement table), each streaming accelerometer, gyroscope, and orientation (quaternion/Euler) data. This supersedes the earlier single 6-axis-IMU placeholder. The current 105-feature vector (99 landmark + 6 zero-filled IMU) is a placeholder and will need to be redesigned around this larger 10-sensor channel set once real sensor recordings are available; IMU_ENABLED remains false until then.", "3–4 weeks, pending hardware recordings"),
      timeline("Continue collecting additional sessions from more participants for ongoing dataset growth.", "Ongoing"),
      timeline("Further accuracy tuning: Class-balanced retraining (v3) brought validation accuracy from 74.38% to 79.27%. Adding 12 joint-angle-derived features and retraining with a two-phase (uniform-sampling then class-balanced + LR-decay) recipe (v5) pushed this to 81.68%, clearing the 80% target. Remaining headroom is expected to come from a larger network and/or real accelerometer/gyroscope data once the new 10-sensor array's firmware streams non-zero values (see Section 5.3 of the User Manual).", "Target met (81.68%); ongoing alongside dataset expansion"),
    ],
  }],
});

function bullet(text, level = 0) {
  return new Paragraph({
    numbering: { reference: "bullets", level },
    spacing: { after: 60 },
    children: [new TextRun(text)],
  });
}

function timeline(text, eta) {
  return new Paragraph({
    numbering: { reference: "timeline", level: 0 },
    spacing: { after: 80 },
    children: [
      new TextRun(text + "  "),
      new TextRun({ text: `(Target: ${eta})`, italics: true, color: "7C3AED" }),
    ],
  });
}

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync("/tmp/docgen/Progress_Report.docx", buffer);
  console.log("written");
});
